language: erlang
otp_release:
       - 18.0
       - 17.0
       - R16B03-1
       - R16B03
       - R16B02
       - R16B01
       - R16B
       - R15B03
script: "DEBUG=1 ./rebar3 update && DEBUG=1 ./rebar3 compile && DEBUG=1 ./rebar3 ct"
branches:
        only:
                - master
notifications:
  email:
    - core@erlware.org
  irc:
    channels:
      - "irc.freenode.org#erlware"
    use_notice: true
    skip_join: true
